import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from performance_optimization_engine.noisy_resume_handler import NoisyResumeHandler  # noqa: E402


def test_repair_collapses_repeated_punctuation():
    handler = NoisyResumeHandler()
    text, report = handler.repair("Section------------Header")
    assert "------------" not in text
    assert report.repeated_punct_collapsed >= 1


def test_repair_removes_orphan_single_char_lines():
    handler = NoisyResumeHandler()
    text = "Deployed models on AWS SageMaker\nn\nAutomated reporting pipeline"
    cleaned, report = handler.repair(text)
    lines = [ln.strip() for ln in cleaned.splitlines()]
    assert "n" not in lines
    assert report.orphan_lines_removed == 1


def test_repair_keeps_normal_text_untouched():
    handler = NoisyResumeHandler()
    text = "Experienced Software Engineer with AWS and SQL skills."
    cleaned, report = handler.repair(text)
    assert "Experienced Software Engineer" in cleaned
    assert report.orphan_lines_removed == 0


def test_repair_report_serializable():
    handler = NoisyResumeHandler()
    _, report = handler.repair("some text")
    d = report.to_dict()
    assert "dictionary_backend" in d


def test_deboilerplate_requires_minimum_corpus_size():
    handler = NoisyResumeHandler()
    docs = ["Line A\nLine B", "Line A\nLine C"]
    cleaned_docs, report = handler.remove_corpus_boilerplate(docs)
    assert cleaned_docs == docs  # too few documents to infer boilerplate
    assert report.boilerplate_lines_removed == []


def test_deboilerplate_removes_repeated_lines_across_corpus():
    handler = NoisyResumeHandler()
    watermark = "Generated by TemplatePro Resume Builder"
    docs = [
        f"John Doe\n{watermark}\nSoftware Engineer",
        f"Jane Smith\n{watermark}\nProduct Manager",
        f"Alex Lee\n{watermark}\nData Scientist",
        f"Sam Kim\n{watermark}\nDesigner",
    ]
    cleaned_docs, report = handler.remove_corpus_boilerplate(docs, min_occurrence_ratio=0.6)
    assert all(watermark not in doc for doc in cleaned_docs)
    assert watermark in report.boilerplate_lines_removed


def test_deboilerplate_preserves_candidate_specific_lines():
    handler = NoisyResumeHandler()
    docs = [
        "John Doe\nSoftware Engineer\nPython, AWS",
        "Jane Smith\nProduct Manager\nSQL, Excel",
        "Alex Lee\nData Scientist\nR, Pandas",
    ]
    cleaned_docs, _ = handler.remove_corpus_boilerplate(docs, min_occurrence_ratio=0.6)
    assert "John Doe" in cleaned_docs[0]
    assert "Jane Smith" in cleaned_docs[1]
